client/src/components/ChipInput.tsx
client/src/components/EventCard.tsx
client/src/components/StyledTextField.tsx
client/src/pages/Home/index.tsx
src/calender/calender.service.ts
src/calender/util/calender.util.ts

DEV-2: added optional fields in book room page

---

client/src/components/Dropdown.tsx
client/src/helpers/cache.ts
client/src/pages/Home/index.tsx

DEV-19: added duration dropdown as user preference

---

client/src/pages/Home/index.tsx
client/src/pages/Login/index.tsx

I have fixed the issue. Hope so it's fine by you

Fixed the Background UI issue

---

client/src/components/Dropdown.tsx
client/src/pages/Home/index.tsx

This PR fixes the issue in #38 and addes the feature request in #52

Fixes #38 and addes feature #52

---

client/src/helpers/cache.ts
client/src/pages/Home/index.tsx

This PR addes the requested feature in #35

feat: added preferred room capacity text field to settings page

---

CONTRIBUTING.md
client/src/api/api.ts
client/src/components/AlertDialog.tsx
client/src/components/Dropdown.tsx
client/src/components/EventCard/EditDialog.tsx
client/src/components/EventCard/EventCard.tsx
client/src/pages/Home/AdvancedOptionsDialog.tsx
client/src/pages/Home/BookRoomView/index.tsx
client/src/pages/Home/SettingsDialog.tsx
client/src/pages/Home/index.tsx
client/src/theme/primitives/colorSchemes.ts
server/src/auth/auth.service.ts
server/src/calender/calender.service.ts
server/src/helpers/google-api-error.mapper.ts
shared/dto/api.response.ts

added abort controller and switched from dialog to box

---

client/src/components/ChipInput.tsx
client/src/components/EventCard/EditDialog.tsx
client/src/helpers/utility.ts
client/src/pages/Home/TopNavigationBar.tsx

- https://github.com/Propo41/bookify/issues/37
- This PR introduces email validation for the ChipInput component, ensuring that only valid email addresses can be added as chips. If the user attempts to add an invalid email, a toast notification is displayed with an error message.
- Since the initial bug was already resolved and removing the invalid email allows the event to be booked, I decided to enhance the user experience by providing immediate feedback when an invalid email is entered. This prevents the user from adding an invalid email in the first place.
- Added email validation logic using the validateEmail utility function before adding the input value to the chips.
- Implemented a toast notification using react-hot-toast to inform users when they attempt to add an invalid email …

feat: validate attendee email

---

client/src/components/EventCard/EditDialog.tsx
client/src/pages/Home/TopNavigationBar.tsx
server/src/calender/calender.controller.ts
shared/dto/get-available-rooms.dto.ts
shared/dto/index.ts
shared/dto/list-rooms.dto.ts
shared/dto/update-event-duration.dto.ts
shared/index.ts

[FEATURE REQ] Add validation layer from client -> server for all routes https://github.com/Propo41/bookify/issues/40
This PR refactors the CalenderController by introducing Data Transfer Objects (DTOs) to handle query parameters more efficiently and provide better validation. The following DTOs have been added:
- UpdateEventDurationDto: For updating the duration of events.
- ListRoomsQueryDto: For querying available rooms with specific time and timezone parameters.
- GetAvailableRoomsQueryDto: For querying available rooms with additional filters like duration, seats, floor, etc.
- Replaced individual Query() decorators with query DTOs for the /rooms and /available-rooms endpoints.
- Applied class-validator decorators to the DTOs for improved input validation.
- Refactored methods in the …

feat: calendar controller validation layer

---

client/src/pages/Home/BookRoomView/index.tsx

added conditional check to compare current time vs formdata time

---

client/src/helpers/utility.ts
client/src/pages/Home/BookRoomView/index.tsx
server/src/calender/calender.controller.ts
server/src/calender/calender.service.ts

added code to check for room availability before booking

---

.github/workflows/build.yml
CONTRIBUTING.md
client/.env.example
client/src/api/api.ts
client/src/config/secrets.ts
client/src/helpers/utility.ts
client/src/pages/Login/index.tsx
server/.env.example
server/src/auth/auth.controller.ts
server/src/auth/auth.service.ts
server/src/auth/oauth.interceptor.ts
server/src/config/env/app.config.ts
server/src/google-api/google-api-mock.service.ts
server/src/google-api/google-api.module.ts
server/src/google-api/google-api.service.ts
server/src/google-api/interfaces/google-api.interface.ts
server/src/helpers/google-api-error.mapper.ts

- resolves #106 
- simplified the mock api initiation by sending the flag only from the client side as header

added a new endpoint to generate the oauth url from api

---

client/src/context/PreferencesContext.tsx

fixed bug preferences not saving due to a redundant conditional block

---

client/src/api/api.ts
client/vite.config.ts

added proxy settings to redirect calls to api server in dev env

---

client/public/manifest.json
client/src/api/api.ts
client/src/pages/Home/MyEventsView/index.tsx
client/src/pages/Home/index.tsx
server/src/auth/auth.controller.ts
server/src/auth/auth.guard.ts
server/src/auth/auth.service.ts
server/src/auth/interfaces/request.interface.ts
server/src/calender/calender.controller.ts
server/src/calender/calender.service.ts
shared/dto/event.response.ts

added restriction to disable editing events not organized

---

client/src/helpers/utility.ts

- resolves #140
- The less than or equal operator used

fix: rooms capacity generated upto max limit(#140)

---

client/generate-manifest.js
client/src/context/PreferencesContext.tsx
client/src/pages/Home/MyEventsView/index.tsx
server/src/google-api/google-api.service.ts

excluded out-of-office events from calender events list

---

client/src/components/AttendeeInput.tsx

resolves #172 
- Bulk Email Input: Users can now paste multiple emails (separated by comma or space) into the attendees box and press Enter to add them all at once.
- Email Validation: Added checks to ensure emails are correctly formatted.
- Duplicate Prevention: Implemented logic to prevent adding duplicate emails.

Multiple email pasting feature added.

---

client/src/helpers/utility.ts
client/src/pages/Home/BookRoomView/index.tsx

- Changed method of population of times from current time to start of the day. 
- Added getNearestTime method to get the nearest time of current time when booking an event.

Added a method to fixed time selecting issue

---

client/src/components/EventCard.tsx
client/src/index.tsx
client/src/pages/Home/BookRoomView/index.tsx
client/src/pages/Home/MyEventsView/DateNavigator.tsx
client/src/pages/Home/MyEventsView/DatePickerPopper.tsx
client/src/pages/Home/MyEventsView/EditEventsView.tsx
client/src/pages/Home/MyEventsView/index.tsx
package-lock.json

 pressing the date title in my events page should open up a date picker modal

---

.prettierrc
client/src/components/AttendeeInput.tsx
client/src/helpers/types.ts
client/src/helpers/utility.ts
client/src/pages/Home/BookRoomView/index.tsx
client/src/pages/Home/MyEventsView/EditEventsView.tsx
client/src/pages/Home/MyEventsView/index.tsx
server/src/calender/calender.controller.ts
server/src/calender/calender.service.ts
server/src/google-api/google-api.service.ts
shared/dto/book-room.dto.ts
shared/dto/event.response.ts

- Resolves: #182 
- Shows the Peoples name and Photo (if available).
- For free-form email the first of the email is shown.
- Instead of using the `string[]` of email current implementation utilizes the `IPeopleInformation[]` that provides the information of the people.

Feat/issue 182 Show image name inside the Attendee chip 
